# iOS build workflow for GFX graphics library
name: iOS Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: macos-15

    strategy:
      fail-fast: false
      matrix:
        # build_type: [Release, Debug]
        platform: [macos-15]
        build_type: [Debug]
        include:
          - os: macos-15
            c_compiler: clang
            cpp_compiler: clang++
    env:
      VULKAN_VERSION: 1.3.290.0

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        brew install ninja

    - name: Install Vulkan SDK
      run: |
        wget "https://sdk.lunarg.com/sdk/download/$VULKAN_VERSION/mac/vulkansdk-macos-$VULKAN_VERSION.dmg?Human=true" -O vulkansdk.dmg
        hdiutil attach vulkansdk.dmg
        sudo /Volumes/vulkansdk-macos-$VULKAN_VERSION/InstallVulkan.app/Contents/MacOS/InstallVulkan --root $GITHUB_WORKSPACE/vulkansdk-macos-$VULKAN_VERSION --accept-licenses --default-answer --confirm-command install
        hdiutil detach /Volumes/vulkansdk-macos-$VULKAN_VERSION
        echo "VULKAN_SDK_PATH=$GITHUB_WORKSPACE/vulkansdk-macos-$VULKAN_VERSION" >> $GITHUB_ENV
        echo "VULKAN_SDK=$GITHUB_WORKSPACE/vulkansdk-macos-$VULKAN_VERSION" >> $GITHUB_ENV
        echo $GITHUB_ENV

    - name: Configure CMake
      run: |
        cmake -B build \
        -G Ninja \
        -DCMAKE_SYSTEM_NAME=iOS \
        -DCMAKE_OSX_ARCHITECTURES=arm64 \
        -DCMAKE_OSX_DEPLOYMENT_TARGET=13.0 \
        -DCMAKE_IOS_INSTALL_COMBINED=YES \
        -DCMAKE_OSX_SYSROOT=iphonesimulator \
        -DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DBUILD_WEBGPU_BACKEND=OFF \
        -DBUILD_VULKAN_BACKEND=ON \
        -DBUILD_EXAMPLES=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_CPP_WRAPPER=ON

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} -j 2

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-arm64-${{ matrix.build_type }}-libraries
        path: |
          build_ios_arm64/libgfx.a
          build_ios_arm64/libgfx_cpp.a
        retention-days: 7
